---
title: "Análisis de Adicción a Redes Sociales"
output:
    flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    social: menu
    source_code: embed
---
```{r setup, include=FALSE}
# Configuración global
library(flexdashboard)
datos_estudiantes = read.table("datos_estudiantes.csv", 
                                header=TRUE, sep=",", dec=".", 
                                stringsAsFactors = TRUE)
```

Descripción General
==================================================================
```{r child="descripcion_general.Rmd"}
```

Uso de Plataformas y Adicción
==================================================================
```{r child="analisis_adiccion_plataformas.Rmd"}
```

Impacto en la Salud
==================================================================
```{r child="analisis_impacto_salud.Rmd"}
```

Impacto Académico
==================================================================
```{r child="analisis_impacto_academico.Rmd"}
```

Perfil Sociodemográfico
==================================================================
```{r child="analisis_sociodemografico.Rmd"}
```

Interacciones inter-variables
==================================================================
```{r child="analisis_dinamicas_relacionales.Rmd"}
```

